### PR TITLE
Fixed Fortify issues:

### PR DESCRIPTION
**Pull request by charlietritran**
- Risky Resource Management, CWE ID 022

### CODE REVIEW

**Comment by dstenger** [comment]
@keshav-nangare Can you please test this pull request?

**Comment by keshavnangare** [comment]
@dstenger 

Is there any service available to test this PR?

**Comment by dstenger** [comment]
You can use this service (although it is no DGIWG WMS): http://cite.deegree.org/deegree-webservices-3.4.5/services/wms130?service=WMS&request=GetCapabilities
So, some tests will fail but you can compare if the failures with and without this pull request are the same.

**Comment by keshavnangare** [comment]
@dstenger 

I have tested this PR  with and without PR with the above service and got the different result. There are lots of test with name `wmsCapabilitiesLayerCrs_Mandatory_CRS_84_Supported` getting failed.

Updated the PR and removed the function `FilenameUtils.normalize()` applied to xpath and tested with updated changes and got the appropriate result.

This PR should be ignored as its breaking some tests. I will create PR by removing those suggested changes.

**Comment by keshavnangare** [comment]
PR #15 should be used instead of current PR and should be ignored.

**Pull request closed without merging**
